name: Sync Repository

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Config Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add remote and force push to organization repo
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          echo "Adding remote repository..."
          git remote add org https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/Exp0tech1/Eduai-Teacher.git
          
          echo "Fetching from remote..."
          git fetch org
          
          echo "Force pushing to remote..."
          git push -u org main --force
