name: Sync Repo to Organization

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to org repository
        run: |
          git remote add org-origin https://github.com/Exp0tech1/Eduai-Teacher
          git push org-origin main