name: Sync Repository

on:
  push:
    branches: [ main ]  # سيعمل عند كل دفع للفرع الرئيسي
  schedule:
    - cron: '0 */6 * * *'  # سيعمل كل 6 ساعات
  workflow_dispatch:  # للتشغيل اليدوي

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:      # تحديد الصلاحيات بشكل صريح
      contents: write # صلاحية الكتابة على المحتوى
      pull-requests: write # صلاحية إنشاء وتعديل pull requests

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync Fork
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/St0ckfish/Eduai-Teacher"  # مستودعك الشخصي
          source_branch: "main"
          destination_repo: "https://github.com/Exp0tech1/Eduai-Teacher" # مستودع المنظمة
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}